export const SET_RIFF_SERVER_ROOM_ID = 'SET_RIFF_SERVER_ROOM_ID';
export const SET_JITSI_UID_FOR_RIFF_SERVER = 'SET_JITSI_UID_FOR_RIFF_SERVER';
export const SET_JITSI_USERNAME_FOR_RIFF_SERVER = 'SET_JITSI_USERNAME_FOR_RIFF_SERVER';
export const SET_SELECTED_MEETING = 'SET_SELECTED_MEETING';
export const DASHBOARD_FETCH_MEETING_STATS = 'DASHBOARD_FETCH_MEETING_STATS';
export const SET_RIFF_FIREBASE_CREDENTIALS = 'SET_RIFF_FIREBASE_CREDENTIALS';
