export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const MEETINGS_REQUEST = 'MEETINGS_REQUEST';
export const MEETINGS_SUCCESS = 'MEETINGS_SUCCESS';
export const MEETINGS_FAILURE = 'MEETINGS_FAILURE';
export const MEETING_RESET = 'MEETING_RESET';

export const MEETING_REQUEST = 'MEETING_REQUEST';
export const MEETING_SUCCESS = 'MEETING_SUCCESS';
export const MEETING_FAILURE = 'MEETING_FAILURE';

export const SCHEDULER_REQUEST = 'SCHEDULER_REQUEST';
export const SCHEDULER_SUCCESS = 'SCHEDULER_SUCCESS';
export const SCHEDULER_FAILURE = 'SCHEDULER_FAILURE';
export const SCHEDULER_RESET = 'SCHEDULER_RESET';

export const SET_RIFF_SERVER_ROOM_ID = 'SET_RIFF_SERVER_ROOM_ID';

export const RESET_REQUEST = 'RESET_REQUEST';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const RESET_FAILURE = 'RESET_FAILURE';
export const RESET_HIDE_MESSAGE = 'RESET_HIDE_MESSAGE';

export const SET_MEETINGS_LIST_TYPE = 'SET_MEETINGS_LIST_TYPE';

export const UPDATE_SCHEDULER_REQUEST = 'UPDATE_SCHEDULER_REQUEST';
export const UPDATE_SCHEDULER_SUCCESS = 'UPDATE_SCHEDULER_SUCCESS';
export const UPDATE_SCHEDULER_FAILURE = 'UPDATE_SCHEDULER_FAILURE';
export const UPDATE_SCHEDULER_RESET = 'UPDATE_SCHEDULER_RESET';

export const TOGGLE_MEETING_MEDIATOR = 'TOGGLE_MEETING_MEDIATOR';
